version: '3.1'
services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql
  app:
    build: .
    depends_on:
      - cassandra
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_CASSANDRA_PORT=9042
    ports:
      - "8080:8080"